name: "Build and Push to GHCR"

on:
  push:
    tags:
      - "go-webapp-ghcr@v[0-9].[0-9]+.[0-9]"

env:
  GHCR_TOKEN: ${{ secrets.GHCR_TOKEN }}
  CONTAINER_NAME: lucjosin/go-webapp-ghcr
  USER_NAME: LucJosin

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Set up checkout
        uses: actions/checkout@v4

      - name: Set up latest git tag
        working-directory: blog/actions-containers-ghcr/go-webapp-ghcr
        run: |
          RAW_TAG="${GITHUB_REF#refs/tags/}"
          VERSION="${RAW_TAG#*@}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
          echo "Version: $VERSION"

      # --- Build Stage ---

      - name: Docker build
        run: |
          docker build -t ghcr.io/${{ env.CONTAINER_NAME }}:latest .
          docker build -t ghcr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }} .

      # --- Push Stage ---

      - name: GitHub (GHCR) login
        run: echo $GHCR_TOKEN | docker login ghcr.io -u $USER_NAME --password-stdin

      - name: GitHub (GHCR) push
        run: |
          docker push ghcr.io/${{ env.CONTAINER_NAME }}:latest
          docker push ghcr.io/${{ env.CONTAINER_NAME }}:${{ env.VERSION }}
